### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by priya-mohan** [theSage21/pytongue#4]
hello,
I came across your article about pytongue i have installed python3, Git, and made a directory and followed to git clone command and made all necessary steps and wrote a hello world program in Hindi , i Used gedit and saved the program in pytongue directory, I have a problem in running the program, when i give pytongue.sh hello.py it says command not found error.

can you please help me

**Comment by theSage21** [comment]
Are you calling pytongue like this  
`$ pytongue.sh hello.py`
as opposed to
`$ ./pytongue.sh hello.py`

The `./` tells the terminal to look in the current directory.

**Comment by priya-mohan** [comment]
Iam running the hello.py program from the same directory in which the pytongue.sh file is located
I have logged as root user-
 root@ubuntu:/pytongue/pytongue# pytongue.sh hello.py
pytongue.sh: command not found 

if i login as normal user then also i get the same error
sameer@ubuntu:/pytongue/pytongue$ pytongue.sh hello.py
pytongue.sh: command not found

**Comment by theSage21** [comment]
Instead of this `sameer@ubuntu:/pytongue/pytongue$ pytongue.sh hello.py`
you should be typing `sameer@ubuntu:/pytongue/pytongue$ ./pytongue.sh
hello.py`

The dot and slash in front of the command is needed to run the script.

The root user is not needed.

**Comment by priya-mohan** [comment]
It worked Thank you..!

**Comment by theSage21** [comment]
I am glad someone found this useful. :smile:
