### ISSUE TITLE
how to connect the module to make it work

### ISSUE THREAD

**Issue by Juicy-Fruit** [theSage21/pytongue#6]
Hello, how to connect the module to make it work if you can for points (to put in the folder; to write a script that imports or something else that is required) if you can video instructions in Windows 

Of course I was surprised at the wrong keywords, but I liked the idea

**Comment by theSage21** [comment]
I'm not sure what you mean. If you're looking for instructions to set this up and running, it is provided in the [README file](https://github.com/theSage21/pytongue/blob/master/README.md).
